[package]
name = "astli-lint"
description = "SystemVerilog lint rules over astli's syntax tree"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
include = ["src/**/*"]

[lints]
workspace = true

[dependencies]
rowan.workspace = true
rustc-hash.workspace = true
astli-parse.workspace = true
astli-sema.workspace = true
astli-syntax.workspace = true
astli-text.workspace = true

[dev-dependencies]
astli-preproc.workspace = true
expect-test.workspace = true
regex.workspace = true
