//! The reserved word set, and the identifier-to-keyword lookup.
//!
//! # One version, kept behind a parameter
//!
//! SystemVerilog's reserved words are version-dependent: under
//! `` `begin_keywords "1364-1995" `` a file's `logic` and `class` are ordinary
//! identifiers. Only the 1800-2023 set is implemented, and the directive is
//! ignored -- see `docs/limitations.md`.
//!
//! [`KeywordVersion`] exists anyway. It costs an argument today, and it is the
//! difference between adding a table and restructuring the lexer if that
//! assumption turns out to be wrong.

use std::sync::LazyLock;

use rustc_hash::FxHashMap;

use crate::SyntaxKind;

/// Which reserved word set to read a file with.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum KeywordVersion {
    /// IEEE 1800-2023, Annex B.
    #[default]
    V1800_2023,
}

/// Every identifier in a file is looked up here, so this is the hottest thing
/// in the lexer -- it measured at roughly 45% of lexing time when it bisected
/// [`KEYWORDS_1800_2023`] instead.
pub static INDEX_1800_2023: LazyLock<FxHashMap<&'static str, SyntaxKind>> =
    LazyLock::new(|| KEYWORDS_1800_2023.iter().copied().collect());

/// Maps an identifier to its keyword kind, or `None` if it is just a name.
///
/// Only ever called with the text of a [`SyntaxKind::IDENT`]. Escaped
/// identifiers must not be passed here: `\logic` is a name, which is the whole
/// point of the escape.
pub fn lookup(ident: &str, version: KeywordVersion) -> Option<SyntaxKind> {
    let index = match version {
        KeywordVersion::V1800_2023 => &*INDEX_1800_2023,
    };
    index.get(ident).copied()
}

/// Spelling of a keyword kind, or `None` if the kind is not a keyword.
pub fn text(kind: SyntaxKind) -> Option<&'static str> {
    if kind == SyntaxKind::ONE_STEP_KW {
        return Some("1step");
    }
    KEYWORDS_1800_2023
        .iter()
        .find(|&&(_, k)| k == kind)
        .map(|&(text, _)| text)
}

/// The IEEE 1800-2023 reserved words (Annex B), and the source of truth from
/// which [`INDEX_1800_2023`] is built.
///
/// `1step` is absent: it begins with a digit, so it never reaches the
/// identifier path and is lexed directly as [`SyntaxKind::ONE_STEP_KW`].
pub const KEYWORDS_1800_2023: &[(&str, SyntaxKind)] = &[
    ("accept_on", SyntaxKind::ACCEPT_ON_KW),
    ("alias", SyntaxKind::ALIAS_KW),
    ("always", SyntaxKind::ALWAYS_KW),
    ("always_comb", SyntaxKind::ALWAYS_COMB_KW),
    ("always_ff", SyntaxKind::ALWAYS_FF_KW),
    ("always_latch", SyntaxKind::ALWAYS_LATCH_KW),
    ("and", SyntaxKind::AND_KW),
    ("assert", SyntaxKind::ASSERT_KW),
    ("assign", SyntaxKind::ASSIGN_KW),
    ("assume", SyntaxKind::ASSUME_KW),
    ("automatic", SyntaxKind::AUTOMATIC_KW),
    ("before", SyntaxKind::BEFORE_KW),
    ("begin", SyntaxKind::BEGIN_KW),
    ("bind", SyntaxKind::BIND_KW),
    ("bins", SyntaxKind::BINS_KW),
    ("binsof", SyntaxKind::BINSOF_KW),
    ("bit", SyntaxKind::BIT_KW),
    ("break", SyntaxKind::BREAK_KW),
    ("buf", SyntaxKind::BUF_KW),
    ("bufif0", SyntaxKind::BUFIF0_KW),
    ("bufif1", SyntaxKind::BUFIF1_KW),
    ("byte", SyntaxKind::BYTE_KW),
    ("case", SyntaxKind::CASE_KW),
    ("casex", SyntaxKind::CASEX_KW),
    ("casez", SyntaxKind::CASEZ_KW),
    ("cell", SyntaxKind::CELL_KW),
    ("chandle", SyntaxKind::CHANDLE_KW),
    ("checker", SyntaxKind::CHECKER_KW),
    ("class", SyntaxKind::CLASS_KW),
    ("clocking", SyntaxKind::CLOCKING_KW),
    ("cmos", SyntaxKind::CMOS_KW),
    ("config", SyntaxKind::CONFIG_KW),
    ("const", SyntaxKind::CONST_KW),
    ("constraint", SyntaxKind::CONSTRAINT_KW),
    ("context", SyntaxKind::CONTEXT_KW),
    ("continue", SyntaxKind::CONTINUE_KW),
    ("cover", SyntaxKind::COVER_KW),
    ("covergroup", SyntaxKind::COVERGROUP_KW),
    ("coverpoint", SyntaxKind::COVERPOINT_KW),
    ("cross", SyntaxKind::CROSS_KW),
    ("deassign", SyntaxKind::DEASSIGN_KW),
    ("default", SyntaxKind::DEFAULT_KW),
    ("defparam", SyntaxKind::DEFPARAM_KW),
    ("design", SyntaxKind::DESIGN_KW),
    ("disable", SyntaxKind::DISABLE_KW),
    ("dist", SyntaxKind::DIST_KW),
    ("do", SyntaxKind::DO_KW),
    ("edge", SyntaxKind::EDGE_KW),
    ("else", SyntaxKind::ELSE_KW),
    ("end", SyntaxKind::END_KW),
    ("endcase", SyntaxKind::ENDCASE_KW),
    ("endchecker", SyntaxKind::ENDCHECKER_KW),
    ("endclass", SyntaxKind::ENDCLASS_KW),
    ("endclocking", SyntaxKind::ENDCLOCKING_KW),
    ("endconfig", SyntaxKind::ENDCONFIG_KW),
    ("endfunction", SyntaxKind::ENDFUNCTION_KW),
    ("endgenerate", SyntaxKind::ENDGENERATE_KW),
    ("endgroup", SyntaxKind::ENDGROUP_KW),
    ("endinterface", SyntaxKind::ENDINTERFACE_KW),
    ("endmodule", SyntaxKind::ENDMODULE_KW),
    ("endpackage", SyntaxKind::ENDPACKAGE_KW),
    ("endprimitive", SyntaxKind::ENDPRIMITIVE_KW),
    ("endprogram", SyntaxKind::ENDPROGRAM_KW),
    ("endproperty", SyntaxKind::ENDPROPERTY_KW),
    ("endsequence", SyntaxKind::ENDSEQUENCE_KW),
    ("endspecify", SyntaxKind::ENDSPECIFY_KW),
    ("endtable", SyntaxKind::ENDTABLE_KW),
    ("endtask", SyntaxKind::ENDTASK_KW),
    ("enum", SyntaxKind::ENUM_KW),
    ("event", SyntaxKind::EVENT_KW),
    ("eventually", SyntaxKind::EVENTUALLY_KW),
    ("expect", SyntaxKind::EXPECT_KW),
    ("export", SyntaxKind::EXPORT_KW),
    ("extends", SyntaxKind::EXTENDS_KW),
    ("extern", SyntaxKind::EXTERN_KW),
    ("final", SyntaxKind::FINAL_KW),
    ("first_match", SyntaxKind::FIRST_MATCH_KW),
    ("for", SyntaxKind::FOR_KW),
    ("force", SyntaxKind::FORCE_KW),
    ("foreach", SyntaxKind::FOREACH_KW),
    ("forever", SyntaxKind::FOREVER_KW),
    ("fork", SyntaxKind::FORK_KW),
    ("forkjoin", SyntaxKind::FORKJOIN_KW),
    ("function", SyntaxKind::FUNCTION_KW),
    ("generate", SyntaxKind::GENERATE_KW),
    ("genvar", SyntaxKind::GENVAR_KW),
    ("global", SyntaxKind::GLOBAL_KW),
    ("highz0", SyntaxKind::HIGHZ0_KW),
    ("highz1", SyntaxKind::HIGHZ1_KW),
    ("if", SyntaxKind::IF_KW),
    ("iff", SyntaxKind::IFF_KW),
    ("ifnone", SyntaxKind::IFNONE_KW),
    ("ignore_bins", SyntaxKind::IGNORE_BINS_KW),
    ("illegal_bins", SyntaxKind::ILLEGAL_BINS_KW),
    ("implements", SyntaxKind::IMPLEMENTS_KW),
    ("implies", SyntaxKind::IMPLIES_KW),
    ("import", SyntaxKind::IMPORT_KW),
    ("incdir", SyntaxKind::INCDIR_KW),
    ("include", SyntaxKind::INCLUDE_KW),
    ("initial", SyntaxKind::INITIAL_KW),
    ("inout", SyntaxKind::INOUT_KW),
    ("input", SyntaxKind::INPUT_KW),
    ("inside", SyntaxKind::INSIDE_KW),
    ("instance", SyntaxKind::INSTANCE_KW),
    ("int", SyntaxKind::INT_KW),
    ("integer", SyntaxKind::INTEGER_KW),
    ("interconnect", SyntaxKind::INTERCONNECT_KW),
    ("interface", SyntaxKind::INTERFACE_KW),
    ("intersect", SyntaxKind::INTERSECT_KW),
    ("join", SyntaxKind::JOIN_KW),
    ("join_any", SyntaxKind::JOIN_ANY_KW),
    ("join_none", SyntaxKind::JOIN_NONE_KW),
    ("large", SyntaxKind::LARGE_KW),
    ("let", SyntaxKind::LET_KW),
    ("liblist", SyntaxKind::LIBLIST_KW),
    ("library", SyntaxKind::LIBRARY_KW),
    ("local", SyntaxKind::LOCAL_KW),
    ("localparam", SyntaxKind::LOCALPARAM_KW),
    ("logic", SyntaxKind::LOGIC_KW),
    ("longint", SyntaxKind::LONGINT_KW),
    ("macromodule", SyntaxKind::MACROMODULE_KW),
    ("matches", SyntaxKind::MATCHES_KW),
    ("medium", SyntaxKind::MEDIUM_KW),
    ("modport", SyntaxKind::MODPORT_KW),
    ("module", SyntaxKind::MODULE_KW),
    ("nand", SyntaxKind::NAND_KW),
    ("negedge", SyntaxKind::NEGEDGE_KW),
    ("nettype", SyntaxKind::NETTYPE_KW),
    ("new", SyntaxKind::NEW_KW),
    ("nexttime", SyntaxKind::NEXTTIME_KW),
    ("nmos", SyntaxKind::NMOS_KW),
    ("nor", SyntaxKind::NOR_KW),
    ("noshowcancelled", SyntaxKind::NOSHOWCANCELLED_KW),
    ("not", SyntaxKind::NOT_KW),
    ("notif0", SyntaxKind::NOTIF0_KW),
    ("notif1", SyntaxKind::NOTIF1_KW),
    ("null", SyntaxKind::NULL_KW),
    ("or", SyntaxKind::OR_KW),
    ("output", SyntaxKind::OUTPUT_KW),
    ("package", SyntaxKind::PACKAGE_KW),
    ("packed", SyntaxKind::PACKED_KW),
    ("parameter", SyntaxKind::PARAMETER_KW),
    ("pmos", SyntaxKind::PMOS_KW),
    ("posedge", SyntaxKind::POSEDGE_KW),
    ("primitive", SyntaxKind::PRIMITIVE_KW),
    ("priority", SyntaxKind::PRIORITY_KW),
    ("program", SyntaxKind::PROGRAM_KW),
    ("property", SyntaxKind::PROPERTY_KW),
    ("protected", SyntaxKind::PROTECTED_KW),
    ("pull0", SyntaxKind::PULL0_KW),
    ("pull1", SyntaxKind::PULL1_KW),
    ("pulldown", SyntaxKind::PULLDOWN_KW),
    ("pullup", SyntaxKind::PULLUP_KW),
    ("pulsestyle_ondetect", SyntaxKind::PULSESTYLE_ONDETECT_KW),
    ("pulsestyle_onevent", SyntaxKind::PULSESTYLE_ONEVENT_KW),
    ("pure", SyntaxKind::PURE_KW),
    ("rand", SyntaxKind::RAND_KW),
    ("randc", SyntaxKind::RANDC_KW),
    ("randcase", SyntaxKind::RANDCASE_KW),
    ("randsequence", SyntaxKind::RANDSEQUENCE_KW),
    ("rcmos", SyntaxKind::RCMOS_KW),
    ("real", SyntaxKind::REAL_KW),
    ("realtime", SyntaxKind::REALTIME_KW),
    ("ref", SyntaxKind::REF_KW),
    ("reg", SyntaxKind::REG_KW),
    ("reject_on", SyntaxKind::REJECT_ON_KW),
    ("release", SyntaxKind::RELEASE_KW),
    ("repeat", SyntaxKind::REPEAT_KW),
    ("restrict", SyntaxKind::RESTRICT_KW),
    ("return", SyntaxKind::RETURN_KW),
    ("rnmos", SyntaxKind::RNMOS_KW),
    ("rpmos", SyntaxKind::RPMOS_KW),
    ("rtran", SyntaxKind::RTRAN_KW),
    ("rtranif0", SyntaxKind::RTRANIF0_KW),
    ("rtranif1", SyntaxKind::RTRANIF1_KW),
    ("s_always", SyntaxKind::S_ALWAYS_KW),
    ("s_eventually", SyntaxKind::S_EVENTUALLY_KW),
    ("s_nexttime", SyntaxKind::S_NEXTTIME_KW),
    ("s_until", SyntaxKind::S_UNTIL_KW),
    ("s_until_with", SyntaxKind::S_UNTIL_WITH_KW),
    ("scalared", SyntaxKind::SCALARED_KW),
    ("sequence", SyntaxKind::SEQUENCE_KW),
    ("shortint", SyntaxKind::SHORTINT_KW),
    ("shortreal", SyntaxKind::SHORTREAL_KW),
    ("showcancelled", SyntaxKind::SHOWCANCELLED_KW),
    ("signed", SyntaxKind::SIGNED_KW),
    ("small", SyntaxKind::SMALL_KW),
    ("soft", SyntaxKind::SOFT_KW),
    ("solve", SyntaxKind::SOLVE_KW),
    ("specify", SyntaxKind::SPECIFY_KW),
    ("specparam", SyntaxKind::SPECPARAM_KW),
    ("static", SyntaxKind::STATIC_KW),
    ("string", SyntaxKind::STRING_KW),
    ("strong", SyntaxKind::STRONG_KW),
    ("strong0", SyntaxKind::STRONG0_KW),
    ("strong1", SyntaxKind::STRONG1_KW),
    ("struct", SyntaxKind::STRUCT_KW),
    ("super", SyntaxKind::SUPER_KW),
    ("supply0", SyntaxKind::SUPPLY0_KW),
    ("supply1", SyntaxKind::SUPPLY1_KW),
    ("sync_accept_on", SyntaxKind::SYNC_ACCEPT_ON_KW),
    ("sync_reject_on", SyntaxKind::SYNC_REJECT_ON_KW),
    ("table", SyntaxKind::TABLE_KW),
    ("tagged", SyntaxKind::TAGGED_KW),
    ("task", SyntaxKind::TASK_KW),
    ("this", SyntaxKind::THIS_KW),
    ("throughout", SyntaxKind::THROUGHOUT_KW),
    ("time", SyntaxKind::TIME_KW),
    ("timeprecision", SyntaxKind::TIMEPRECISION_KW),
    ("timeunit", SyntaxKind::TIMEUNIT_KW),
    ("tran", SyntaxKind::TRAN_KW),
    ("tranif0", SyntaxKind::TRANIF0_KW),
    ("tranif1", SyntaxKind::TRANIF1_KW),
    ("tri", SyntaxKind::TRI_KW),
    ("tri0", SyntaxKind::TRI0_KW),
    ("tri1", SyntaxKind::TRI1_KW),
    ("triand", SyntaxKind::TRIAND_KW),
    ("trior", SyntaxKind::TRIOR_KW),
    ("trireg", SyntaxKind::TRIREG_KW),
    ("type", SyntaxKind::TYPE_KW),
    ("typedef", SyntaxKind::TYPEDEF_KW),
    ("union", SyntaxKind::UNION_KW),
    ("unique", SyntaxKind::UNIQUE_KW),
    ("unique0", SyntaxKind::UNIQUE0_KW),
    ("unsigned", SyntaxKind::UNSIGNED_KW),
    ("until", SyntaxKind::UNTIL_KW),
    ("until_with", SyntaxKind::UNTIL_WITH_KW),
    ("untyped", SyntaxKind::UNTYPED_KW),
    ("use", SyntaxKind::USE_KW),
    ("uwire", SyntaxKind::UWIRE_KW),
    ("var", SyntaxKind::VAR_KW),
    ("vectored", SyntaxKind::VECTORED_KW),
    ("virtual", SyntaxKind::VIRTUAL_KW),
    ("void", SyntaxKind::VOID_KW),
    ("wait", SyntaxKind::WAIT_KW),
    ("wait_order", SyntaxKind::WAIT_ORDER_KW),
    ("wand", SyntaxKind::WAND_KW),
    ("weak", SyntaxKind::WEAK_KW),
    ("weak0", SyntaxKind::WEAK0_KW),
    ("weak1", SyntaxKind::WEAK1_KW),
    ("while", SyntaxKind::WHILE_KW),
    ("wildcard", SyntaxKind::WILDCARD_KW),
    ("wire", SyntaxKind::WIRE_KW),
    ("with", SyntaxKind::WITH_KW),
    ("within", SyntaxKind::WITHIN_KW),
    ("wor", SyntaxKind::WOR_KW),
    ("xnor", SyntaxKind::XNOR_KW),
    ("xor", SyntaxKind::XOR_KW),
];
