[package]
name = "astli-parse"
description = "Event-based parser building a lossless SystemVerilog syntax tree"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
rowan.workspace = true
rustc-hash.workspace = true
astli-preproc.workspace = true
astli-syntax.workspace = true
astli-text.workspace = true

[dev-dependencies]
expect-test.workspace = true
ungrammar.workspace = true
