[package]
name = "astli-preproc"
description = "Directives, macro expansion, and `include resolution for SystemVerilog"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
include = ["src/**/*"]

[lints]
workspace = true

[dependencies]
rustc-hash.workspace = true
astli-syntax.workspace = true
astli-text.workspace = true
